### ISSUE TITLE
Border-radius not being applied when using artwork:cover

### ISSUE THREAD

**Issue by syphernl** [kalkih/mini-media-player#190]
My mini-media-player configs uses `artwork:cover` but when it does the configured border radius of the theme doesn't get applied. 

Once I comment out the artwork it properly shows rounded corners, but with artwork configured it is always square.

Is this something that should work out of the box or does this require card-mod magic to get to work?

**Comment by kalkih** [comment]
Hey,
This should work out of the box, was actually fixed in the latest release [v1.4.2](https://github.com/kalkih/mini-media-player/releases/tag/v1.4.2).
Make sure you're not loading an older version of the card from cache, try manually clearing the browser cache.

If you're using HACS, please check kalkih/mini-graph-card/issues/169, same information is relevant for this card.

**Comment by syphernl** [comment]
I have checked:
- Installed version: `v1.4.2`
- Including it like this:  
```
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
```

**Comment by kalkih** [comment]
Please send me your card config so I can try to reproduce.
Try reinstalling the card, try in incognito mode and see if the issue persist.

**Comment by syphernl** [comment]
> Please send me your card config so I can try to reproduce.
> Try reinstalling the card, try in incognito mode and see if the issue persist.

This is my config:
```
  - type: conditional
    conditions:
      - entity: media_player.music
        state: "playing"
    card:
      type: custom:mini-media-player
      entity: media_player.music
      info: scroll
      artwork: cover
      hide:
        icon: true
        power: true
        volume: true
        shuffle: false
```

**Comment by jackwilsdon** [comment]
I'm still seeing this problem with v1.4.2 (installed manually):

<img width="1658" src="https://user-images.githubusercontent.com/1843197/69915281-2e482380-1445-11ea-9142-0876b393184c.png">

## System

**Home Assistant**: 0.102.2
**OS**: macOS High Sierra (10.13.6)
**Browser**: Google Chrome 78.0.3904.108 (Official Build) (64-bit)

## Configuration

```YAML
artwork: cover
entity: media_player.bedroom
name: Sonos
type: 'custom:mini-media-player'
```

**Comment by kalkih** [comment]
Strange, I'll update my HA to 1.02 later tonight to see and make sure this didn't break with that update.

Try clearing your cache / re-download the card to make sure you're loading the latest version.
When installing cards manually I really recommend adding the new version number to the end of the resource url path after updating, to ensure the previous version isn't loaded from cache .
```yaml
resources:
  - url: /local/mini-media-player-bundle.js?v=1.4.2
    type: module
```

**Comment by jackwilsdon** [comment]
I've never installed any other version than v1.4.2, and I've already got the version in the URL path as you suggested, so I don't think there's any issue there.

After doing a bit more testing, I can only reproduce this on Chrome - it doesn't occur in Firefox 70.0.1.

**Comment by jackwilsdon** [comment]
So it looks like the `border-radius` is not applied to `ha-card` in Chrome for some reason (I can't even tell where the rounded corners are coming from in Chrome) - adding it to `mmp__bg` fixes the issue but is somewhat of a hack due to the `border-radius` missing from its `ha-card` parent.

**Comment by kalkih** [comment]
How do you apply the border radius, with the variable `ha-card-border-radius` set in your theme?

The border-radius is applied to the nested ha-card elements, this was made because we needed the content of `.mmp__player` to be able to overflow `ha-card` if I remember correctly.

Here's the lines setting the border-radius, I see there's a typo though, `mmp__player` should be `mmp-player`.
https://github.com/kalkih/mini-media-player/blob/b68ceb1cd18fee8ccee90cf7f94433ffe296b999/src/style.js#L63-L67

Border radius is working for me in chrome though, exact same version number as you as well and MacOS.

![Screenshot 2019-12-01 at 19 28 04](https://user-images.githubusercontent.com/457678/69918317-bf80bf80-1470-11ea-85bd-7464e558a772.png)

In my theme:
```yaml
ha-card-border-radius: 4px
```

**Comment by jackwilsdon** [comment]
Ah sorry if I made it unclear — I don't have any custom theming, my observations were just from inspecting the DOM (you can probably just ignore what I said, it's likely wrong).

**Comment by kalkih** [comment]
Aha, I see.
You're right though, when inspecting the DOM in chrome dev-tools I can't see the border-radius property set anywhere either, very strange 🤔
But it does seem to work anyway, dev-tools bug maybe?

But yeah, the reason why it's set in the nested elements of `ha-card` instead of directly in `ha-card` is because we want one of the nested elements to be allowed to overflow `ha-card`, idk if that makes sense?

**Comment by vanlooverenkoen** [comment]
@kalkih can't get the border radius to work. 
my theme:
```
media_player_lovelace:
  ha-card-border-radius: 4px
```

my lovelace ui:
```
type: 'custom:mini-media-player'
entity: media_player.kitchen_display
theme: media_player_lovelace
```

**Comment by loocd** [comment]
I just had a very similar issue on one HA installation. I had to entries in my Settings>Dashboards>Resources (one of them I believe was from the HACS installation, one I added manually.

Removed both of them, then removed the mini-media-player card in HACS and after that reinstalled it.

Now it works as expected.
