### ISSUE TITLE
Source name and source selector are not on the same line

### ISSUE THREAD

**Issue by bieniu** [kalkih/mini-media-player#325]
When `mini-media-player` is grouped in entities card source name and source selector are not on the same line.

![image](https://user-images.githubusercontent.com/478555/83605107-a23fc180-a577-11ea-88a4-8eac81af66de.png)

Configuration:
```
          - type: entities
            show_header_toggle: false
            state_color: true
            entities:
              - light.bulbs_salon
              - light.leds_salon
              - light.lamp_salon
              - input_select.light_scenes_salon
              - input_select.salon_harmony
              - type: custom:mini-media-player
                entity: media_player.bravia
                hide:
                  controls: true
                  volume: true
                  power: true
                  progress: true
                info: scroll
                group: true
```

**Comment by kalkih** [comment]
Hello, this was fixed in v1.9.0, see #310, #305

**Comment by bieniu** [comment]
@kalkih Sorry, I didn't write which version I use. Issue is with version 1.9.1.

**Comment by kalkih** [comment]
What HA version are you on?
Some troubleshooting steps:
* Press the three dot menu in the HA header bar at the top and press reload resources.
* Clear cache
* Make sure the resource reference to the card  is correct.
* Reinstall the card if installed through HACS

**Comment by bieniu** [comment]
I'm using HA 0.110.4, the cache has been clreared several times and I have used "private mode" in the browser, the card has been uninstalled and installed again by HACS, the resources definition is correct and resources have been reloaded. Issue still exists.

Resources definition:
```
lovelace:
  mode: yaml
  resources:
    - url: ...
      type: ...
    - url: ...
      type: ...
    - url: ...
      type: ...
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
```

**Comment by kalkih** [comment]
Thanks, I see it now as well, seems to only be the source/sound mode dropdown chevron, will fix.

**Comment by kalkih** [comment]
New release with this fix is now available.
